name: Dev-Release

on:
  create:
    branches:
      - "dev"
    tags:
      - "*"

jobs:
  test:
    name: Dev release ubuntu-latest Py3.9
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Additional info about the build
      shell: bash
      run: |
        uname -a
        df -h
        ulimit -a
    # More info on options: https://github.com/conda-incubator/setup-miniconda
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.9
        environment-file: devtools/conda-envs/test_env.yaml
        activate-environment: test
        auto-update-conda: false
        auto-activate-base: false
        show-channel-urls: true
    - name: Install package
      # conda setup requires this special shell
      shell: bash -l {0}
      run: |
        python -m pip install . --no-deps
        conda list
    - name: Run linters
      shell: bash -l {0}
      run: |
        black --check --diff packmol_step tests
        flake8 packmol_step tests
    - name: Run tests
      shell: bash -l {0}
      run: |
        pytest -v --cov=packmol_step --cov-report=xml --color=yes tests/
    - name: CodeCov
      uses: codecov/codecov-action@v2
      with:
        file: ./coverage.xml
        flags: unittests
    - name: Install pypa/build
      run: |
        python -m pip install build --user
    - name: Build a binary wheel and a source tarball
      if: github.ref_type == 'tag'
      run: |
        python -m build --sdist --wheel --outdir dist/
        ls -l dist/
    - name: Publish distribution 📦 to Test PyPI
      # Only publish tagged versions with 'dev' or 'rc' in the tag.
      if: github.ref_type == 'tag' && contains(github.ref, 'dev') == true || contains(github.ref, 'rc') == true
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.pypi_password }}
        skip_existing: true
