name: Release

on:
  release:
    types: [published]
    branches:
      - "main"

jobs:
  release:
    name: Release
    uses: molssi-seamm/devops/.github/workflows/Release.yaml@main
    with:
      src : packmol_step
    secrets: inherit

  docker:
    name: Docker
    needs: release
    uses: molssi-seamm/devops/.github/workflows/Docker.yaml@main
    with:
      image : molssi-seamm/seamm-packmol
      description: A Packmol executable packaged for use with SEAMM or standalone
    secrets: inherit
